In [1]:
import numpy as np
import scipy.linalg

In [2]:
A1 = np.array([[-9,  3, -7, -2, -4],
              [ 6, -6,  2,  4,  2],
              [-5,  3, -3, -2, -2]])
print(A1)

[[-9  3 -7 -2 -4]
 [ 6 -6  2  4  2]
 [-5  3 -3 -2 -2]]


In [ ]:
# L should be 3x3 and U 3x5

In [3]:
L1 = np.array([[   1,    0,   0],
              [-2/3,    1,   0],
              [ 5/9, -1/3,  1]])
print(L1)

[[ 1.          0.          0.        ]
 [-0.66666667  1.          0.        ]
 [ 0.55555556 -0.33333333  1.        ]]


In [4]:
U1 = np.array([[-9,  3,   -7,  -2,   -4],
              [ 0, -4, -8/3, 8/3, -2/3],
              [ 0,  0,    0,   0,    0]])
print(U1)

[[-9.          3.         -7.         -2.         -4.        ]
 [ 0.         -4.         -2.66666667  2.66666667 -0.66666667]
 [ 0.          0.          0.          0.          0.        ]]


In [5]:
# check if our L and U are correct
A2 = np.dot(L1, U1)
print(A2); print(A1)

[[-9.  3. -7. -2. -4.]
 [ 6. -6.  2.  4.  2.]
 [-5.  3. -3. -2. -2.]]
[[-9  3 -7 -2 -4]
 [ 6 -6  2  4  2]
 [-5  3 -3 -2 -2]]


In [6]:
# verify with the scipy LU decomposition
P, L, U = scipy.linalg.lu(A1)
# permutation matrix P is the identity in this example
L.shape, U.shape

((3, 3), (3, 5))

In [7]:
print(L); print(U)

[[ 1.          0.          0.        ]
 [-0.66666667  1.          0.        ]
 [ 0.55555556 -0.33333333  1.        ]]
[[-9.00000000e+00  3.00000000e+00 -7.00000000e+00 -2.00000000e+00
  -4.00000000e+00]
 [ 0.00000000e+00 -4.00000000e+00 -2.66666667e+00  2.66666667e+00
  -6.66666667e-01]
 [ 0.00000000e+00  0.00000000e+00  4.19417587e-16  0.00000000e+00
   0.00000000e+00]]


In [8]:
A3 = np.dot(L,U)
print(A3); print(A1)

[[-9.  3. -7. -2. -4.]
 [ 6. -6.  2.  4.  2.]
 [-5.  3. -3. -2. -2.]]
[[-9  3 -7 -2 -4]
 [ 6 -6  2  4  2]
 [-5  3 -3 -2 -2]]


In [ ]:
# now let's look at a tall matrix (transposed A from above and slides)

In [9]:
A4 = np.array([[-9,  6, -5],
              [ 3, -6,  3],
              [-7,  2, -3],
              [-2,  4, -2],
              [-4,  2, -2]])
print(A4)

[[-9  6 -5]
 [ 3 -6  3]
 [-7  2 -3]
 [-2  4 -2]
 [-4  2 -2]]


In [10]:
# L should be 5x5 and U 5x3

In [11]:
L4 = np.array([[  1,   0,   0,  0, 0],
              [-1/3,   1,   0,  0, 0],
              [ 7/9,  2/3,   1,  0, 0],
              [ 2/9, -2/3,   0,  1, 0],
              [ 4/9,  1/6,   0,  0, 1]])
print(L4)

[[ 1.          0.          0.          0.          0.        ]
 [-0.33333333  1.          0.          0.          0.        ]
 [ 0.77777778  0.66666667  1.          0.          0.        ]
 [ 0.22222222 -0.66666667  0.          1.          0.        ]
 [ 0.44444444  0.16666667  0.          0.          1.        ]]


In [12]:
U4 = np.array([[-9, 6,  -5],
              [0, -4, 4/3],
              [0,  0,  0],
              [0,  0,  0],
              [0,  0,  0]])
print(U4)

[[-9.          6.         -5.        ]
 [ 0.         -4.          1.33333333]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [13]:
# check if our L and U are correct
A5 = np.dot(L4,U4)
print(A5); print(A4)

[[-9.  6. -5.]
 [ 3. -6.  3.]
 [-7.  2. -3.]
 [-2.  4. -2.]
 [-4.  2. -2.]]
[[-9  6 -5]
 [ 3 -6  3]
 [-7  2 -3]
 [-2  4 -2]
 [-4  2 -2]]


In [14]:
P, L, U = scipy.linalg.lu(A4)
# permutation matrix P is the identity in this example
L.shape, U.shape

((5, 3), (3, 3))

In [15]:
# are truncated to  m x min(m,n)  and  min(m,n) x n
print(L); print(U )

[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [ 0.77777778  0.66666667  1.        ]
 [ 0.22222222 -0.66666667 -0.34375   ]
 [ 0.44444444  0.16666667  0.25      ]]
[[-9.00000000e+00  6.00000000e+00 -5.00000000e+00]
 [ 0.00000000e+00 -4.00000000e+00  1.33333333e+00]
 [ 0.00000000e+00  0.00000000e+00 -3.94745964e-16]]


In [16]:
A5 = np.dot(L,U)
print(A5); print(A4)

[[-9.  6. -5.]
 [ 3. -6.  3.]
 [-7.  2. -3.]
 [-2.  4. -2.]
 [-4.  2. -2.]]
[[-9  6 -5]
 [ 3 -6  3]
 [-7  2 -3]
 [-2  4 -2]
 [-4  2 -2]]
